# Generated by Django 4.2.4 on 2023-08-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Littlelemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
